# Default setup is given for MySQL with ruby1.9.
# Examples for PostgreSQL, SQLite3 and SQL Server can be found at the end.
# Line indentation must be 2 spaces (no tabs).

production:
  adapter: mysql2
  database: reese
  host: localhost
  username: portal
  password: F5P&DS#dKd4RsaTv8q
  encoding: utf8